services:
  backend:
    build:
      context: ./Backend
    container_name: myPortfolio-backend
    restart: always
    networks:
      - main_network
    ports:
      - "127.0.0.1:5051:5051"
    volumes:
      - /root/main/portfolio/backend/logs:/app/logs
      - /root/main/portfolio/backend/.env:/app/.env
      - /root/main/portfolio/backend/google:/app/google
      - /root/main/portfolio/backend/emaildata.js:/app/emaildata.js
    environment:
      - DB_HOST=main_db
      - BACKEND_ORIGIN=https://api.msliwowski.net
  app:
    build:
      context: ./Frontend
    container_name: myPortfolio-frontend
    restart: always
    networks:
      - main_network
    ports:
      - "127.0.0.1:5050:80"
    environment:
      - FRONTEND_ORIGIN=https://msliwowski.net
    

networks:
  main_network:
    external: true
    name: main_network