services:
  backend:
    build:
      context: ./Backend
    container_name: myPortfolio-backend
    restart: always
    networks:
      - main_network
    ports:
      - "5051:5051"
    volumes:
      - /root/main/portfolio/backend/logs:/app/logs
      - /root/main/portfolio/backend/.env:/app/.env
    environment:
      - DB_HOST=main_db

  #  App:
  #   build:
  #     context: ./Frontend
  #     contaner_name: myPortfolio-frontend
  #     restart: always
  #     networks:
  #         - main_network
  #     ports:
  #       - "5050:5050"
  #   

networks:
  main_network:
    external: true
    name: main_network